#!/bin/bash
# HOME="/home/troy"
export EDITOR="emacs"

########## Begin Rails development funtions ########################
# Rails change directory functions
CURRENT_APP_NAME="vehicle_22"
CURRENT_APP_NAME="depot"
CURRENT_APP_DIR="${HOME}/devel/rails/${CURRENT_APP_NAME}/"
CURRENT_RAILS_GIT_DIR="$CURRENT_APP_DIR/vendor/rails-ads-vehicles"

r () {
    echo "db => ${EDITOR} ${CURRENT_APP_DIR}/db/schema.rb"
    echo "cr => cd current rails app"
    echo "crv => cd current rails app, app/views"
    echo "crg => current Rails Git dir"
    echo "rgc => git clone git@github.com:troywill/rails-ads-vehicles"
}
db () {
    ${EDITOR} ${CURRENT_APP_DIR}/db/schema.rb
}

rgc () {
    git clone git@github.com:troywill/rails-ads-vehicles
}
cr () {
    cd ${CURRENT_APP_DIR}
}
crv () {
    cd ${CURRENT_APP_DIR}/app/views
}
crg () {
    cd ${CURRENT_RAILS_GIT_DIR}
}

########## End Rails development funtions ########################
## Begin section: Git functions ##
g () {
    echo "Git functions"
    echo "ga => git add $1"
    echo "gb => git branch --color -a"
    echo "gpu => git push origin user"
}
gpu () {
    git push origin user
}
gb () {
    git branch --color -a
}
ga () {
    echo "==> git add $1"
    git add $1
}
## End section: Git functions ##

# Networking aliases
n () {
    tdw-wireless-daemon
}
# alias n='tdw-wireless-daemon'

# Change directory functions

t-csv () {
    cd ${HOME}/rcs/stowball/data/shilohSchema/2010_spring/csv
    git pull
    /bin/ls --color
}

t-scripts () {
    cd /var/lib/stowball/data/scripts
    /bin/ls --color
}

u () {
    cd ${HOME}/rcs/stowball/utilities
    /bin/ls --color
}

eb () {
    BASHRC="$HOME/.bashrc"
    $EDITOR $BASHRC && source $BASHRC
}

tz () {
    echo "tar -xf $1" && tar -xf $1
}

alias ebd='pwd >> /etc/bashrc; emacs /etc/bashrc && source /etc/bashrc'
alias dog='git pull; git commit -a; push origin master'
alias doggy="git pull; git commit -a -m 'minor'; git push origin master"
alias csb='cd ~/rcs/stowball && ./stowball-write-db-from-csv'
alias f1='find . -cmin -1 -type f'
alias f5='find . -cmin -5 -type f'
alias f60='find . -cmin -60 -type f'

alias d='emacs .';
alias e='emacs'
alias c='clear && /bin/ls --color'
alias cl='rm --verbose *~; /bin/ls --color'
alias ..='cd .. && clear && ls'
alias 2='cd /home/troy/rcs/stowball/data/shilohSchema/2010_spring/csv'

alias rcs='cd /home/troy/rcs && ls --color'

t-arora-google () {
    arora "http://www.google.com/search?hl=C&q=${1}" &
}

# pacman functions
p () {
    sudo pacman --sync $1
}
