#!/bin/bash
# HOME="/home/troy"
export EDITOR="emacs"

#### Begin Rails development funtions ####
# Rails change directory functions
CURRENT_APP_NAME="vehicle_22"
CURRENT_APP_NAME="depot"
CURRENT_APP_NAME="cards"
CURRENT_APP_NAME="marvscars"
CURRENT_APP_DIR="${HOME}/devel/rails/${CURRENT_APP_NAME}/"

# r () {
#     echo "db => ${EDITOR} ${CURRENT_APP_DIR}/db/schema.rb"
#     echo "cr => cd current rails app"
#     echo "crv => cd current rails app, app/views"
#     echo "rgc => git clone git@github.com:troywill/rails-ads-vehicles"
#     echo "rrp => git clone git@github.com:troywill/rails-rapid-prototype"
#     echo "glayouts => git clone git@github.com:troywill/tdw-css"

# }
rrp () {
    git clone git@github.com:troywill/rails-rapid-prototype
}

glayouts () {
    git clone git@github.com:troywill/tdw-css
}

rgc () {
    git clone git@github.com:troywill/rails-ads-vehicles
}
db () {
    ${EDITOR} ${CURRENT_APP_DIR}/db/schema.rb
}
cr () {
    cd ${CURRENT_APP_DIR}
}
crv () {
    cd ${CURRENT_APP_DIR}/app/views
}

#### End Rails development funtions ####
#### Begin section: Git functions ##
g () {
    echo "Git functions"
    echo "gca => git commit --all"
    echo "gpu => git push origin user"
    echo "rrp => git push origin user"
    echo "gpom => git push origin master"
    echo "gb => git branch --color -a"
}
gca () {
    git commit --all
}
gpu () {
    git push origin user
}
gb () {
    git branch --color -a
}
gpom () {
    echo "==> git push origin master" && git push origin master
}
#### End section: Git functions ##

#### Change directory functions

t-s () {
    DAY=`date +%d`;
    DIR="${HOME}/success/2011/05/${DAY}"
    mkdir --parent ${DIR}
    cd ${DIR}
}

t-csv () {
    cd ${HOME}/rcs/stowball/data/shilohSchema/2010_spring/csv
    git pull
    /bin/ls --color
}

t-scripts () {
    cd /var/lib/stowball/data/scripts
    /bin/ls --color
}

u () {
    cd ${HOME}/rcs/stowball/utilities
    /bin/ls --color
}

eb () {
    BASHRC="$HOME/.bashrc"
    $EDITOR $BASHRC && source $BASHRC
}

tz () {
    echo "tar -xf $1" && tar -xf $1
}

alias ebd='pwd >> /etc/bashrc; emacs /etc/bashrc && source /etc/bashrc'
alias dog='git pull; git commit -a; push origin master'
alias doggy="git pull; git commit -a -m 'minor'; git push origin master"
alias csb='cd ~/rcs/stowball && ./stowball-write-db-from-csv'
alias f1='find . -cmin -1 -type f'
alias f5='find . -cmin -5 -type f'
alias f60='find . -cmin -60 -type f'

alias d='emacs .';
alias e='emacs'
alias c='clear && /bin/ls --color'
alias cl='rm --verbose *~; /bin/ls --color'
alias ..='cd .. && clear && ls --color'

alias rcs='cd /home/troy/rcs && ls --color'

t-arora-google () {
    arora "http://www.google.com/search?hl=C&q=${1}" &
}

# pacman functions
p () {
    sudo pacman --sync $1
}


