#!/bin/bash
# HOME="/home/troy"
export EDITOR="emacs"

#### Begin Rails development funtions ####
# Rails change directory functions
CURRENT_APP_NAME="marvscars"
CURRENT_APP_DIR="${HOME}/devel/rails/${CURRENT_APP_NAME}/"

# r () {
#     echo "db => ${EDITOR} ${CURRENT_APP_DIR}/db/schema.rb"
#     echo "cr => cd current rails app"
#     echo "crv => cd current rails app, app/views"
#     echo "rgc => git clone git@github.com:troywill/rails-ads-vehicles"
#     echo "rrp => git clone git@github.com:troywill/rails-rapid-prototype"
#     echo "glayouts => git clone git@github.com:troywill/tdw-css"

# }
rrp () {
    git clone git@github.com:troywill/rails-rapid-prototype
}

glayouts () {
    git clone git@github.com:troywill/css-tdw
}

rgc () {
    git clone git@github.com:troywill/rails-ads-vehicles
}
db () {
    ${EDITOR} ${CURRENT_APP_DIR}/db/schema.rb
}
cr () {
    cd ${CURRENT_APP_DIR}
}
crv () {
    cd ${CURRENT_APP_DIR}/app/views
}

#### End Rails development funtions ####
#### Begin section: Git functions ##
g () {
    echo "Git functions"
    echo "gca => git commit --all"
    echo "gpu => git push origin user"
    echo "rrp => git push origin user"
    echo "gpom => git push origin master"
    echo "gb => git branch --color -a"
}
gca () {
    git commit --all
}
gpu () {
    git push origin user
}
gb () {
    git branch --color -a
}
gpom () {
    echo "==> git push origin master" && git push origin master
}
#### End section: Git functions ##

#### Change directory functions

t-s () {
    DAY=`date +%d`;
    DIR="${HOME}/success/2011/08/${DAY}"
    mkdir --parent ${DIR}
    cd ${DIR}
    emacs "actions-2011-08-${DAY}.txt"
}

tz () {
    echo "tar -xf $1" && tar -xf $1
}

alias dog='git pull; git commit -a; push origin master'
alias doggy="git pull; git commit -a -m 'minor'; git push origin master"
alias csb='cd ~/rcs/stowball && ./stowball-write-db-from-csv'
alias f1='find . -cmin -1 -type f'
alias d1='find . -cmin -1 -type d'
alias f5='find . -cmin -5 -type f'
alias d5='find . -cmin -5 -type d'
alias f60='find . -cmin -60 -type f | grep -v chromium | grep -v macromedia'

alias d='emacs .';
alias e='emacs'
alias c='clear && /bin/ls --color'
alias cl='rm --verbose *~; rm -rvf ~/.emacs_backups; /bin/ls --color'
alias ..='cd .. && clear && ls --color'

#### Ruby/Rails testing functions
rtf () {
    echo "rake test:functionals" && rake test:functionals
}
